version: '3.8'

services:

  rabbitmq:
    build: ./rabbitmq
    container_name: 'rabbitmq3'
    ports:
      - '15672:15672'
      - '5672:5672'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 10s
      timeout: 10s
      retries: 3

  manager:
    build: ./manager
    container_name: 'manager'
    ports:
      - '8080:8080'
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq

  worker:
    build: ./worker
    deploy:
      mode: replicated
      replicas: 2 # change number of workers
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq